"use client";

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";

const API_URL =
    process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api/v1";

interface Intervention {
    id: string;
    type: "HOLD" | "DEPLOY" | "SURGE" | "EXPRESS";
    priority: "critical" | "high" | "medium" | "low";
    status: "pending" | "approved" | "dismissed";
    headline: string;
    description: string;
    route_id: string;
    route_name: string;
    trigger: string;
    vehicle_id: string | null;
    target_stop: string | null;
    hold_seconds: number | null;
    depot_name: string | null;
    passengers_affected: number;
    wait_time_impact_seconds: number;
    confidence: number;
    latitude: number;
    longitude: number;
    created_at: string;
}

interface InterventionSummary {
    total: number;
    pending: number;
    approved: number;
    dismissed: number;
    critical: number;
    high: number;
}

const TYPE_ICONS: Record<string, string> = {
    HOLD: "⏸",
    DEPLOY: "🚌",
    SURGE: "⚡",
    EXPRESS: "🏃",
};

const TYPE_COLORS: Record<string, string> = {
    HOLD: "#F59E0B",     // Amber
    DEPLOY: "#EF4444",   // Red
    SURGE: "#8B5CF6",    // Purple
    EXPRESS: "#06B6D4",  // Cyan
};

const PRIORITY_COLORS: Record<string, string> = {
    critical: "#EF4444",
    high: "#F97316",
    medium: "#EAB308",
    low: "#6B7280",
};

/**
 * CommandConsole — The Intervention Engine UI.
 *
 * Shows actionable interventions generated by BusIQ's autonomous
 * operations engine. Each intervention is a specific, one-click
 * action: HOLD a bus, DEPLOY from depot, SURGE capacity.
 *
 * This is the core differentiator — not "here's a problem" but
 * "here's what to do about it."
 */
export default function CommandConsole({
    onFlyTo,
}: {
    onFlyTo?: (lat: number, lon: number) => void;
}) {
    const [interventions, setInterventions] = useState<Intervention[]>([]);
    const [summary, setSummary] = useState<InterventionSummary | null>(null);
    const [expanded, setExpanded] = useState(true);
    const [actioningId, setActioningId] = useState<string | null>(null);
    const [filter, setFilter] = useState<string | null>(null); // null = all

    const fetchInterventions = useCallback(async (refresh = false) => {
        try {
            const url = `${API_URL}/ops/interventions${refresh ? "?refresh=true" : ""}`;
            const resp = await fetch(url);
            if (!resp.ok) return;
            const json = await resp.json();
            setInterventions(json.data?.interventions || []);
            setSummary(json.data?.summary || null);
        } catch {
            // Silently fail
        }
    }, []);

    useEffect(() => {
        fetchInterventions(true); // Initial load with refresh
        const interval = setInterval(() => fetchInterventions(true), 30000);
        return () => clearInterval(interval);
    }, [fetchInterventions]);

    const handleAction = async (id: string, action: "approve" | "dismiss") => {
        setActioningId(id);
        try {
            const resp = await fetch(`${API_URL}/ops/interventions/${id}`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ action }),
            });
            if (resp.ok) {
                // Update local state immediately
                setInterventions((prev) =>
                    prev.map((i) =>
                        i.id === id ? { ...i, status: action === "approve" ? "approved" : "dismissed" } : i
                    )
                );
            }
        } catch {
            // ignore
        } finally {
            setActioningId(null);
        }
    };

    const pendingInterventions = interventions.filter(
        (i) => i.status === "pending" && (!filter || i.type === filter)
    );
    const actionedInterventions = interventions.filter(
        (i) => i.status !== "pending"
    );
    const pendingCount = interventions.filter((i) => i.status === "pending").length;

    return (
        <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ type: "spring", stiffness: 400, damping: 30 }}
            className="absolute top-44 sm:top-48 left-4 sm:left-6 z-40 w-72 sm:w-80"
            style={{ maxHeight: "calc(100vh - 230px)" }}
        >
            <div className="glass p-3 flex flex-col" style={{ maxHeight: "calc(100vh - 230px)" }}>
                {/* Header */}
                <button
                    onClick={() => setExpanded(!expanded)}
                    className="w-full flex items-center justify-between mb-2"
                >
                    <div className="flex items-center gap-2">
                        <div
                            className="w-2 h-2 rounded-full animate-pulse"
                            style={{
                                backgroundColor:
                                    pendingCount > 0 ? "#EF4444" : "#22C55E",
                            }}
                        />
                        <span
                            className="text-xs font-semibold tracking-widest uppercase"
                            style={{ color: "var(--text-primary)" }}
                        >
                            Command Console
                        </span>
                    </div>
                    <div className="flex items-center gap-2">
                        {pendingCount > 0 && (
                            <span
                                className="text-[10px] font-bold px-1.5 py-0.5 rounded-full"
                                style={{
                                    backgroundColor: "rgba(239, 68, 68, 0.2)",
                                    color: "#EF4444",
                                }}
                            >
                                {pendingCount}
                            </span>
                        )}
                        <span
                            className="text-[10px]"
                            style={{ color: "var(--text-tertiary)" }}
                        >
                            {expanded ? "▲" : "▼"}
                        </span>
                    </div>
                </button>

                {/* Summary bar */}
                {summary && (
                    <div className="flex items-center gap-2 mb-2 pb-2 border-b border-white/5">
                        {summary.critical > 0 && (
                            <span
                                className="text-[10px] font-bold px-1.5 py-0.5 rounded"
                                style={{
                                    backgroundColor: "rgba(239, 68, 68, 0.15)",
                                    color: "#EF4444",
                                }}
                            >
                                {summary.critical} CRITICAL
                            </span>
                        )}
                        {summary.high > 0 && (
                            <span
                                className="text-[10px] font-bold px-1.5 py-0.5 rounded"
                                style={{
                                    backgroundColor: "rgba(249, 115, 22, 0.15)",
                                    color: "#F97316",
                                }}
                            >
                                {summary.high} HIGH
                            </span>
                        )}
                        {summary.approved > 0 && (
                            <span
                                className="text-[10px] px-1.5 py-0.5 rounded"
                                style={{
                                    backgroundColor: "rgba(34, 197, 94, 0.15)",
                                    color: "#22C55E",
                                }}
                            >
                                ✓ {summary.approved}
                            </span>
                        )}
                    </div>
                )}

                <AnimatePresence>
                    {expanded && (
                        <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: "auto", opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.2 }}
                            className="overflow-y-auto flex-1"
                            style={{ maxHeight: "calc(100vh - 240px)" }}
                        >
                            {/* Type filter pills */}
                            <div className="flex items-center gap-1 mb-2">
                                <button
                                    onClick={() => setFilter(null)}
                                    className="text-[10px] px-2 py-0.5 rounded-full transition-colors"
                                    style={{
                                        backgroundColor: !filter
                                            ? "rgba(255,255,255,0.15)"
                                            : "rgba(255,255,255,0.05)",
                                        color: "var(--text-secondary)",
                                    }}
                                >
                                    ALL
                                </button>
                                {(["HOLD", "DEPLOY", "SURGE"] as const).map((t) => (
                                    <button
                                        key={t}
                                        onClick={() =>
                                            setFilter(filter === t ? null : t)
                                        }
                                        className="text-[10px] px-2 py-0.5 rounded-full transition-colors"
                                        style={{
                                            backgroundColor:
                                                filter === t
                                                    ? `${TYPE_COLORS[t]}22`
                                                    : "rgba(255,255,255,0.05)",
                                            color:
                                                filter === t
                                                    ? TYPE_COLORS[t]
                                                    : "var(--text-tertiary)",
                                        }}
                                    >
                                        {TYPE_ICONS[t]} {t}
                                    </button>
                                ))}
                            </div>

                            {/* Pending interventions */}
                            {pendingInterventions.length === 0 ? (
                                <div
                                    className="text-center py-4 text-[11px]"
                                    style={{ color: "var(--text-tertiary)" }}
                                >
                                    <div className="text-lg mb-1">✓</div>
                                    No pending interventions
                                </div>
                            ) : (
                                <div className="space-y-2">
                                    {pendingInterventions.map((intv, idx) => (
                                        <InterventionCard
                                            key={intv.id}
                                            intervention={intv}
                                            index={idx}
                                            isActioning={actioningId === intv.id}
                                            onApprove={() =>
                                                handleAction(intv.id, "approve")
                                            }
                                            onDismiss={() =>
                                                handleAction(intv.id, "dismiss")
                                            }
                                            onFlyTo={() =>
                                                onFlyTo?.(
                                                    intv.latitude,
                                                    intv.longitude
                                                )
                                            }
                                        />
                                    ))}
                                </div>
                            )}

                            {/* Actioned interventions */}
                            {actionedInterventions.length > 0 && (
                                <div className="mt-3 pt-2 border-t border-white/5">
                                    <span
                                        className="text-[10px] font-semibold tracking-wider uppercase mb-1 block"
                                        style={{ color: "var(--text-tertiary)" }}
                                    >
                                        ACTIONED
                                    </span>
                                    <div className="space-y-1">
                                        {actionedInterventions
                                            .slice(0, 3)
                                            .map((intv) => (
                                                <div
                                                    key={intv.id}
                                                    className="flex items-center gap-2 py-1 px-2 rounded"
                                                    style={{
                                                        backgroundColor:
                                                            "rgba(255,255,255,0.03)",
                                                    }}
                                                >
                                                    <span className="text-[10px]">
                                                        {intv.status === "approved"
                                                            ? "✅"
                                                            : "❌"}
                                                    </span>
                                                    <span
                                                        className="text-[10px] truncate flex-1"
                                                        style={{
                                                            color: "var(--text-tertiary)",
                                                        }}
                                                    >
                                                        {intv.headline}
                                                    </span>
                                                </div>
                                            ))}
                                    </div>
                                </div>
                            )}
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </motion.div>
    );
}

// ─── Individual Intervention Card ─── //

function InterventionCard({
    intervention,
    index,
    isActioning,
    onApprove,
    onDismiss,
    onFlyTo,
}: {
    intervention: Intervention;
    index: number;
    isActioning: boolean;
    onApprove: () => void;
    onDismiss: () => void;
    onFlyTo: () => void;
}) {
    const intv = intervention;
    const typeColor = TYPE_COLORS[intv.type] || "#6B7280";
    const priorityColor = PRIORITY_COLORS[intv.priority] || "#6B7280";

    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.05, type: "spring", stiffness: 400, damping: 30 }}
            className="rounded-xl p-2.5 cursor-pointer transition-colors"
            style={{
                backgroundColor: "rgba(255,255,255,0.04)",
                border: `1px solid ${typeColor}22`,
            }}
            onClick={onFlyTo}
        >
            {/* Top row: type badge + priority + route */}
            <div className="flex items-center gap-1.5 mb-1.5">
                <span
                    className="text-[10px] font-bold px-1.5 py-0.5 rounded"
                    style={{
                        backgroundColor: `${typeColor}22`,
                        color: typeColor,
                    }}
                >
                    {TYPE_ICONS[intv.type]} {intv.type}
                </span>
                <span
                    className="text-[10px] font-bold px-1 py-0.5 rounded uppercase"
                    style={{
                        backgroundColor: `${priorityColor}15`,
                        color: priorityColor,
                    }}
                >
                    {intv.priority}
                </span>
                <span
                    className="text-[10px] ml-auto"
                    style={{ color: "var(--text-tertiary)" }}
                >
                    Route {intv.route_name}
                </span>
            </div>

            {/* Headline */}
            <p
                className="text-[11px] font-medium leading-tight mb-1.5"
                style={{ color: "var(--text-primary)" }}
            >
                {intv.headline}
            </p>

            {/* Impact row */}
            <div className="flex items-center gap-2 mb-2">
                <span
                    className="text-[10px]"
                    style={{ color: "var(--text-tertiary)" }}
                >
                    👥 {intv.passengers_affected} pax
                </span>
                {intv.wait_time_impact_seconds < 0 && (
                    <span
                        className="text-[10px]"
                        style={{ color: "#22C55E" }}
                    >
                        ⏱ {Math.abs(Math.round(intv.wait_time_impact_seconds / 60))}min saved
                    </span>
                )}
                <span
                    className="text-[10px] ml-auto"
                    style={{ color: "var(--text-tertiary)" }}
                >
                    {Math.round(intv.confidence * 100)}% conf
                </span>
            </div>

            {/* Action buttons */}
            <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                <button
                    onClick={onApprove}
                    disabled={isActioning}
                    className="flex-1 text-[11px] font-semibold py-1.5 rounded-lg transition-all hover:brightness-110 active:scale-95"
                    style={{
                        backgroundColor: "rgba(34, 197, 94, 0.2)",
                        color: "#22C55E",
                    }}
                >
                    {isActioning ? "..." : "✓ APPROVE"}
                </button>
                <button
                    onClick={onDismiss}
                    disabled={isActioning}
                    className="flex-1 text-[11px] font-semibold py-1.5 rounded-lg transition-all hover:brightness-110 active:scale-95"
                    style={{
                        backgroundColor: "rgba(107, 114, 128, 0.15)",
                        color: "var(--text-tertiary)",
                    }}
                >
                    DISMISS
                </button>
            </div>
        </motion.div>
    );
}
