FROM node:20-alpine

WORKDIR /app/frontend

# Install deps
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy source
COPY frontend/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
